
spring:
  datasource:
    name: srv
    url: jdbc:mysql://127.0.0.1:3306/multiple_webside?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: test
    password: 123456
    # 使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    include: classpath:/application-admin.yml

mybatis:
  mapper-locations: classpath:config/mybatis/mapper/*.xml
  type-aliases-package: cn.cinling.javacommon.database.entity




